version: '3'
services:

  discovery:
    image: tanerdiler/service-discovery
    container_name: service-discovery
    build:
      context: ./containerized-discovery
      dockerfile: Dockerfile
    environment:
      - LOGSTASH_DEST=logstash:5000
    ports:
      - "8761:8761"

  scgateway:
    image: wod-juiz/service-scgateway
    container_name: service-scgateway
    build:
      context: ./containerized-scgateway
      dockerfile: Dockerfile
    ports:
      - "8763:8763"
    environment:
      - LOGSTASH_DEST=logstash:5000

  accounts:
    image: tanerdiler/service-accounts-api
    container_name: service-accounts
    build:
      context: ./containerized-accounts
      dockerfile: Dockerfile
    ports:
      - "2222:2222"
