server:
  port: ${PORT:8761}

eureka:
  shouldUseDns: false
  instance:
    hostname: ${HOST_NAME:localhost}
    preferIpAddress: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${ZONE:http://localhost:8761/eureka}
  server:
    enableSelfPreservation: true
#    maxThreadsForPeerReplication: 0
spring:
  main:
    banner-mode: "off"
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    distribution:
      percentiles-histogram.http.server.requests: false
      percentiles.http.server.requests: 0.5, 0.9, 0.95, 0.99, 0.999
      sla.http.server.requests: 500ms, 2000ms

opentracing:
  jaeger:
    log-spans: false
    http-sender:
       url: ${JAEGER_HTTP_URL:https://localhost:14268/api/traces}
