server:
  port: ${PORT:8763}

spring:
  main:
    banner-mode: "off"
  application:
    name: containerized-scgateway
  metrics:
    distribution:
      percentiles-histogram.http.server.requests: false
      percentiles.http.server.requests: 0.5, 0.9, 0.95, 0.99, 0.999
      sla.http.server.requests: 500ms, 2000ms

  cloud:
    gateway:
      routes:
        - id: containerized-accounts
          uri: lb://CONTAINERIZED-ACCOUNTS
          predicates:
            - Path=/api/**
    loadbalancer:
      ribbon:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    prefer-ip-address: false
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${DISCOVERY:http://localhost:8761/eureka}
